# Generated by Django 2.0.3 on 2018-03-29 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dribble',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 23, 23, 118646, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='facebook',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 23, 23, 117081, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='pinterest',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 23, 23, 118021, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='tumblr',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 23, 23, 118337, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='twitter',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 23, 23, 117434, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='vk',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 23, 23, 117735, tzinfo=utc), null=True),
        ),
    ]
