# Generated by Django 2.0.3 on 2018-03-29 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0002_auto_20180329_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dribble',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 26, 30, 462308, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='facebook',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 26, 30, 460690, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pinterest',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 26, 30, 461690, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='tumblr',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 26, 30, 461992, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 26, 30, 461078, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vk',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 9, 26, 30, 461391, tzinfo=utc), null=True),
        ),
    ]
