# Generated by Django 2.0.3 on 2018-03-14 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('quote', models.TextField(null=True)),
                ('published', models.DateTimeField(default=datetime.datetime(2018, 3, 14, 7, 27, 26, 352269, tzinfo=utc), null=True)),
            ],
        ),
    ]
