# Generated by Django 2.0.3 on 2018-03-14 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 7, 27, 43, 616452, tzinfo=utc), null=True),
        ),
    ]
