# Generated by Django 2.0.3 on 2018-03-14 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180314_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 7, 32, 25, 821561, tzinfo=utc), null=True),
        ),
    ]
