# Generated by Django 2.0.3 on 2018-03-14 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180314_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, upload_to='post_vid'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 8, 1, 45, 570860, tzinfo=utc), null=True),
        ),
    ]
