# Generated by Django 2.0.3 on 2018-03-14 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180314_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('tel', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=300)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 14, 9, 47, 39, 434445, tzinfo=utc), null=True),
        ),
    ]
