# Generated by Django 2.0.3 on 2018-03-17 06:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180314_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='post_pic')),
                ('video', models.FileField(blank=True, upload_to='post_vid')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 17, 6, 3, 11, 737896, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=True, to='news.News'),
        ),
    ]
