# Generated by Django 2.0.3 on 2018-03-17 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180317_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 17, 7, 6, 4, 156694, tzinfo=utc), null=True),
        ),
    ]
