# Generated by Django 2.0.3 on 2018-03-19 07:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180317_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(blank=True, upload_to='post_pic'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 19, 7, 47, 7, 119003, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
