# Generated by Django 2.0.3 on 2018-03-19 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20180319_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='previewImage',
            field=models.ImageField(blank=True, upload_to='preview_pic'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 19, 9, 2, 36, 93876, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
