# Generated by Django 2.0.3 on 2018-03-19 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20180319_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 19, 9, 6, 26, 935163, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, upload_to='post_vid'),
        ),
    ]
