# Generated by Django 2.0.3 on 2018-03-21 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20180321_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 7, 58, 58, 304938, tzinfo=utc), null=True),
        ),
    ]
