# Generated by Django 2.0.3 on 2018-03-21 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20180321_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressClipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 8, 58, 59, 222475, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='pressclipping',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
