# Generated by Django 2.0.3 on 2018-03-21 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20180321_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 9, 16, 2, 520567, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pressclipping',
            name='new',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
