# Generated by Django 2.0.3 on 2018-03-21 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20180321_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressclipping',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 9, 48, 51, 630029, tzinfo=utc), null=True),
        ),
    ]
