# Generated by Django 2.0.3 on 2018-03-21 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20180321_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 9, 50, 56, 330346, tzinfo=utc), null=True),
        ),
    ]
