# Generated by Django 2.0.3 on 2018-03-22 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_auto_20180321_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressclipping',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 6, 27, 52, 248167, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 6, 27, 52, 246976, tzinfo=utc), null=True),
        ),
    ]
