# Generated by Django 2.0.3 on 2018-03-22 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_auto_20180322_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomediabox',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='videomediabox',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 8, 38, 48, 473093, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pressclipping',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 8, 38, 48, 474183, tzinfo=utc), null=True),
        ),
    ]
