# Generated by Django 2.0.3 on 2018-03-22 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20180322_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailus',
            name='sendBack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 9, 31, 29, 656349, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='photomediabox',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 9, 31, 29, 658025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pressclipping',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 9, 31, 29, 657603, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='videomediabox',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 9, 31, 29, 658438, tzinfo=utc)),
        ),
    ]
