# Generated by Django 2.0.3 on 2018-03-29 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_auto_20180329_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dribble',
        ),
        migrations.DeleteModel(
            name='Facebook',
        ),
        migrations.DeleteModel(
            name='Pinterest',
        ),
        migrations.DeleteModel(
            name='Tumblr',
        ),
        migrations.DeleteModel(
            name='Twitter',
        ),
        migrations.DeleteModel(
            name='VK',
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 29, 8, 55, 45, 133999, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='photomediabox',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 8, 55, 45, 135609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pressclipping',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 29, 8, 55, 45, 135183, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='videomediabox',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 8, 55, 45, 136030, tzinfo=utc)),
        ),
    ]
